spring.application.name=empCRUD
spring.datasource.url=jdbc:postgresql://localhost:5433/emp_crud
spring.datasource.username=postgres
spring.datasource.password=Defence@21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
spring.jpa.open-in-view=false