spring.application.name=empCRUD
spring.datasource.url=jdbc:postgresql://localhost:5434/employee
spring.datasource.username=postgres
spring.datasource.password=2588

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true